### ISSUE TITLE
Default Credentials (master, guest, rest)

### ISSUE THREAD

**Issue by warriar** [ogema/ogema#12]
Problem:
The Framework is delivered with default users (master:master, guest:guest, rest:rest).
This can lead to unprotected systems on the internet as Users might not take the time to set strong passwords. Especially the not well documented guest user could remain on systems.

Solution:
Disable all users besides master by default.
Deliver Framework without a master password and force user during setup to set a strong master password.

**Comment by zmansuroglu** [comment]
Already fixed in the SNAPSHOT version. No default users are created. The static user configuration is managed via the con file config/ogema.roles and user can be created dynamically via the frameworkadmin page.
