### ISSUE TITLE
Web privilege escalation

### ISSUE THREAD

**Issue by gramou** [ogema/ogema#15]
1. Login with default username guest and password guest
2. Open "User Administration" page /ogema/frameworkadminindex/index.html#/users
3. Edit guest user and set the checkbox administrator
--> guest is now administrator

**Comment by zmansuroglu** [comment]
This is possible only if ogema is started with disabled security. If security is enabled guest shouldn't be able to get the page /ogema/frameworkadminindex/index.html at all.
