### ISSUE TITLE
Account & Password for demokit

### ISSUE THREAD

**Issue by gdebig** [ogema/ogema#16]
Dear Ogema,

I was try the OGEMA for the first time. I already download the demokit and have it run on my machine. I already get the web login page. However, I can not uses the default account (master/guest/rest) to login in this page. So, what is the current default login?or how to add the account for the demokit?

Regards,

**Comment by cnoelle** [comment]
Hi, you can create a new user via the OSGi shell: "createUser <USER_NAME>"... the initial password will be equal to the user name. View existing users via "listUsers". In a clean start, the users configured in the file <OGEMA_RUNDIR>/config/ogema.roles are created, which should indeed include the master and guest users if you did not edit the file.
