### ISSUE TITLE
add OSGi shell commands for permission debugging

### ISSUE THREAD

**Issue by JanLapp** [ogema/ogema#28]
Added shell commands to add / remove permissions for a bundle and list effective permissions.

**Comment by cnoelle** [comment]
New commands in "ogm"-namespace:
- allow (give a permission to a bundle)
- deny (deny a bundle a permission)
- removePolicy (remove a policy entry by name)
- bundlePermissions (list all permissions applying to a bundle)
- grantLocalPermissions (add all permissions listed in the bundle's permissions.perm file)
- checkLocalPermissions (prints which local permissions of a bundle are allowed, not allowed or denied)
- printLocalPermissions (print a bundle's permissions.perm file)
